<header class="main-header">
    <div>
        <h1 class="">🎬CinéStream +</h1>
        <p class="">Votre cinéma, partout, à tout moment.</p>
    </div>
    
    <nav class="main-nav">
        <a href="index.php?route=index" class="<?= ($route === 'index') ? '' : '' ?>">
           ☰  VIDÉOTHÈQUE
        </a>
        <a href="index.php?route=search" class="<?= ($route === 'show')? '' : '' ?>">
            🔍 RECHERCHE
        </a>
    </nav>
</header>
    