<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>CineStream+ - Ma Vidéothèque</title>
</head>
<body>

<?php require 'header.phtml'; ?>

<main class="container">
    <section class="categories">
        <button class="tag <?php echo empty($_GET['id']) ? 'active' : ''; ?>">
    Tous les films
    </button>
    
    
    </section>

    <?php if (empty($films)): ?>
        <p class="empty-msg">Votre vidéothèque est vide. Commencez votre collection !</p>
    <?php else: ?>
        <div class="movie-grid">
            <?php foreach ($films as $film): ?>
                <div class="card">
                    <a href="index.php?action=show&id=<?= $film['id'] ?>">
                        <img src="https://image.tmdb.org/t/p/w500<?= $film['poster_path'] ?>" 
                             alt="<?= htmlspecialchars($film['title']) ?>">
                    </a>
                    
                    <div class="card-body">
                        <h3><?= htmlspecialchars($film['title']) ?></h3>
                        <p><?= $film['release_date'] ?> • <?= $film['isWatched'] ? '✅ Vu' : '🕒 À voir' ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</main>

</body>
</html>