<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>Document</title>
     
</head>
<body>

<?php require 'header.phtml'; ?>

<main class="container">
    <section class="categories">
        <button class="tag active">Tous les films</button>
        <button class="tag">Action</button>
        <button class="tag">Comédie</button>
        <button class="tag">Drame</button>
        <button class="tag">Fantastic</button>
        <button class="taf">Horreur</button>
        </section>
     
        


    <?php if (empty($films)): ?>
        <p class="empty-msg">Votre vidéothèque est vide. Commencez votre collection !</p>
    <?php else: ?>
        <div class="movie-grid">
            <?php foreach ($films as $film): ?>
                <div class="card">
                    <img src="https://image.tmdb.org/t/p/w500<?= $film['poster_path'] ?>" alt="<?= htmlspecialchars($film['title']) ?>">
                    <div class="card-body">
                        <h3><?= htmlspecialchars($film['title']) ?></h3>
                        <p><?= $film['release_date'] ?> • <?= $film['isWatched'] ? '✅ Vu' : '🕒 À voir' ?></p>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</main>

    
</body>
</html>
