<?php ?>

<a href="javascript:history.back()"><-retour</a>

<h1><?= htmlspecialchars($film['title']) ?></h1>

<img src="<?= Tmdb::IMG_URL . $film['poster_path>'] ?>" alt="<?= htmlspecialchars($film['title']) ?>">

<p><?= !empty($film['release_date'] ) ? substr($film['release_date'],0,4) : 'n/c' ?>
 <?= htmlspecialchars((string) ($film['runtime']?? 'n/c')) ?> min </p>

 <p>note : <?= htmlspecialchars((string) ($film['vote_average'] ?? 'n/c')) ?>/10 </p>

 <p><?=  ?></p>

 

